title: Writing by Double-A
description: I write interactive furry vore literature. If that's not a thing you're interested in reading, I'm not sure what you're doing here.
url: /writing/
github.is_user_page: false
